/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WsIp */

#ifndef _Included_WsIp
#define _Included_WsIp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WsIp
 * Method:    hasIp
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_WsIp_hasIp(JNIEnv *, jclass, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
