#!/usr/bin/env python3

import datetime
import glob
import os
import subprocess
import sys

if len(sys.argv) != 3:
    print("Usage: {} <ipws_path> <ws_path_start>" \
          .format(sys.argv[0]))
    sys.exit(1)

ipws_path, ws_path_start = sys.argv[1:]

weight_system_files = glob.glob(glob.escape(ws_path_start) + "*")

while len(weight_system_files) >= 2:
    next_files = []

    while len(weight_system_files) >= 2:
        paths = weight_system_files[0:30]
        del weight_system_files[0:30]

        fns = [os.path.basename(path) for path in paths]
        dir = os.path.dirname(paths[0])

        ws_path = os.path.join(dir, fns[0] + "+")
        ws_tmp_path = ws_path + ".tmp"

        cmd = [ipws_path, "--combine-ws", "--ws-out", ws_tmp_path] + paths

        print(datetime.datetime.utcnow(), cmd)
        sys.stdout.flush()

        if subprocess.call(cmd, stderr=sys.stdout) == 0:
            os.rename(ws_tmp_path, ws_path)
            # for path in paths:
            #     os.remove(path)

            next_files.append(ws_path)
        else:
            print("failed")
            sys.stdout.flush()
            sys.exit(1)

    weight_system_files.extend(next_files)
