#!/usr/bin/env python3

import datetime
import glob
import os
import subprocess
import sys

if len(sys.argv) != 4:
    print("Usage: {} <ipws_path> <ws_path_start> <move_old_dir>" \
          .format(sys.argv[0]))
    sys.exit(1)

ipws_path, ws_path_start, move_old_dir = sys.argv[1:]

weight_system_files = glob.glob(glob.escape(ws_path_start) + "*")

while len(weight_system_files) >= 2:
    path1 = weight_system_files.pop(0)
    path2 = weight_system_files.pop(0)

    fn1 = os.path.basename(path1)
    fn2 = os.path.basename(path2)
    dir = os.path.dirname(path1)

    ws_path = os.path.join(dir, fn1 + "--" + fn2)
    ws_tmp_path = ws_path + ".tmp"

    cmd = [ipws_path, "--combine-ws", path1, "--ws-in", path2,
           "--ws-out", ws_tmp_path]

    print(datetime.datetime.utcnow(), cmd)
    sys.stdout.flush()

    if subprocess.call(cmd, stderr=sys.stdout) == 0:
        os.rename(ws_tmp_path, ws_path)
        os.rename(path1, os.path.join(move_old_dir, fn1))
        os.rename(path2, os.path.join(move_old_dir, fn2))
    else:
        print("failed")
        sys.stdout.flush()
