---
- name: Copy ipws
  copy:
    src: build-{{ suffix }}/ipws-{{ suffix }}
    dest: "{{ ipws_path }}"
    mode: 0755

- name: Copy pairs
  copy:
    src: data/pairs-{{ suffix }}
    dest: "{{ pairs_path }}"
    mode: 0644

- name: Copy find candidates script
  copy:
    src: find-candidates
    dest: "{{ find_candidates_path }}"
    mode: 0755
