---
- name: Copy ipws
  copy:
    src: build-{{ suffix }}/ipws-{{ suffix }}
    dest: "{{ ipws_path }}"
    mode: 0755

- name: Copy pairs
  copy:
    src: data/pairs-{{ suffix }}
    dest: "{{ pairs_path }}"
    mode: 0644

- name: Copy ipws run script
  copy:
    src: run-ipws
    dest: "{{ run_ipws_path }}"
    mode: 0755
